services:
  # PostgreSQL
  postgres-db:
    container_name: funkos-db_postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
        - ${POSTGRES_PORT}:5432
    volumes:
        - ./database/funkos.sql:/docker-entrypoint-initdb.d/funkos.sql
    networks:
        - funkos-network

    # Adminer para conectarse a la base de datos
  adminer-postgres-db:
    container_name: tienda-db_adminer-postgres-db
    image: adminer
    restart: always
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
    networks:
      - funkos-network

networks:
  funkos-network:
    driver: bridge